linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - exportloopref
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck

build-tags:
  - integrationtest

linters-settings:
  goimports:
    local-prefixes: github.com/ezitisitis/bunny-go

issues:
  exclude-use-default: false
